In [8]:
x = {1, 2, 3}
y = {2, 3, 4}
print(x ^ y)

{1, 4}


In [9]:
a = (1, 2, [3, 4])
a[2].append(5)
print(a)

(1, 2, [3, 4, 5])


In [10]:
A = {1, 2, 3}
B = {2, 3, 4}
print(A & B)

{2, 3}


In [11]:
t = (1, 2, 3)
t[0] = 5

TypeError: 'tuple' object does not support item assignment

In [ ]:
str1 = "Hello, World!"
print(str1[3:8])

lo, W


In [ ]:
nums = [3, 6, 2, 9, 4]
print(min(nums), max(nums), sum(nums) / len(nums))

2 9 4.8


In [ ]:
def add(a, b):
	return a + b

print(add('5', '3'))

53


In [ ]:
nums = [1, 2, 3, 4]
print(nums.pop(2))
print(nums)

3
[1, 2, 4]


In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr), np.median(arr))

2.5 2.5


In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr_reshaped = arr.reshape(4, 2)
print(arr_reshaped)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)

[2 4 6 8]


In [16]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.T)

   0  1  2
A  1  2  3
B  4  5  6


In [17]:
data = {'A': [10, 20, 30], 'B': [40, 50, 60]}
df = pd.DataFrame(data)
print(df.iloc[1, 1])

50


In [18]:
df['C'] = df['A'] + df['B']

In [19]:
arr = np.array([[10, 20], [30, 40]])
print(arr.T)

[[10 30]
 [20 40]]


In [20]:
df1 = {"X":40, "Y":45}
print(list(df1.keys()))

['X', 'Y']


In [21]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.loc[0, 'B'])

4
