# Week 3

**Name:** I Adarsh *(PG-12)*<br>
**Registration Number:** 240905294<br>
**Date:** 04/02/2025

In [2]:
import numpy as np

# Program 1
Generate a 3x4 NumPy array with random integers between 1 and 50.

In [3]:
arr = np.random.randint(1, 51, (3, 4))
arr

array([[11,  1, 34, 48],
       [ 4, 47, 26, 45],
       [10, 33, 18, 20]])

Calculate and print the mean, median, and standard deviation of the array.

In [4]:
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr)}")

Mean: 24.75
Median: 23.0
Standard deviation: 15.99544205912005


Print the sum of all elements and the sum of each row.

In [5]:
print(f"Sum of elements: {np.sum(arr)}")
print(f"Sum of each row: {np.sum(arr, axis=1)}")

Sum of elements: 297
Sum of each row: [ 94 122  81]


Reshape the 3x4 array into a 2x6 array and print it.

In [6]:
print(np.reshape(arr, (2, 6)))

[[11  1 34 48  4 47]
 [26 45 10 33 18 20]]


# Program 2
Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations.

In [7]:
x = np.random.randint(1, 100, (3, 3))
y = np.random.randint(1, 100, (3, 3))
print(f"{x}\n\n{y}")

[[66 93  9]
 [79 12 10]
 [85 33 41]]

[[39 29 78]
 [45 20 20]
 [61 64 72]]


Matrix addition

In [8]:
print(x + y)

[[105 122  87]
 [124  32  30]
 [146  97 113]]


Matrix subtraction

In [9]:
print(x - y)

[[ 27  64 -69]
 [ 34  -8 -10]
 [ 24 -31 -31]]


Matrix multiplication (element-wise and dot product)

In [10]:
print(f"Element-wise:\n{x * y}")
print(f"\nDot product:\n{x @ y}")

Element-wise:
[[2574 2697  702]
 [3555  240  200]
 [5185 2112 2952]]

Dot product:
[[ 7308  4350  7656]
 [ 4231  3171  7122]
 [ 7301  5749 10242]]


Transpose of a matrix

In [11]:
print(f"X transpose:\n{x.T}")
print(f"\nY transpose:\n{y.T}")

X transpose:
[[66 79 85]
 [93 12 33]
 [ 9 10 41]]

Y transpose:
[[39 45 61]
 [29 20 64]
 [78 20 72]]


Determinant and inverse (if applicable)

In [12]:
print(f"Determinant of X:{np.linalg.det(x)}")
print(f"Determinant of Y:{np.linalg.det(y)}")
print(f"\nX inverse:\n{np.linalg.inv(x)}")
print(f"\nY inverse:\n{np.linalg.inv(y)}")

Determinant of X:-197201.99999999974
Determinant of Y:77140.0

X inverse:
[[-0.00082149  0.01782943 -0.00416831]
 [ 0.01211448 -0.0098427  -0.00025862]
 [-0.00804759 -0.02904129  0.03324003]]

Y inverse:
[[ 0.00207415  0.03764584 -0.01270417]
 [-0.02618616 -0.02527871  0.0353902 ]
 [ 0.02151932 -0.00942442 -0.00680581]]
