# Week 3

**Name:** I Adarsh *(PG-12)*<br>
**Registration Number:** 240905294<br>
**Date:** 04/02/2025

In [20]:
import numpy as np

# Program 1
Generate a 3x4 NumPy array with random integers between 1 and 50.

In [21]:
arr = np.random.randint(1, 50, (3, 4))
arr

array([[40,  9, 26,  2],
       [12, 21, 10, 37],
       [31, 13, 49, 47]])

Calculate and print the mean, median, and standard deviation of the array.

In [22]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

24.75
23.5
15.286840746210448


Print the sum of all elements and the sum of each row.

In [23]:
print(np.sum(arr))
print(np.sum(arr, axis=0))

297
[83 43 85 86]


Reshape the 3x4 array into a 2x6 array and print it.

In [24]:
print(np.reshape(arr, (2, 6)))

[[40  9 26  2 12 21]
 [10 37 31 13 49 47]]


# Program 2
Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations.

In [25]:
x = np.random.randint(1, 100, (3, 3))
y = np.random.randint(1, 100, (3, 3))
print(x)
print()
print(y)

[[17 39 83]
 [64 42 42]
 [73 10 19]]

[[28 55 16]
 [57 98 77]
 [14  3 57]]


Matrix addition

In [26]:
print(x + y)

[[ 45  94  99]
 [121 140 119]
 [ 87  13  76]]


Matrix subtraction

In [27]:
print(x - y)

[[-11 -16  67]
 [  7 -56 -35]
 [ 59   7 -38]]


Matrix multiplication (element-wise and dot product)

In [28]:
print(x @ y)

[[3861 5006 8006]
 [4774 7762 6652]
 [2880 5052 3021]]


Transpose of a matrix

In [29]:
print(x.T)
print()
print(y.T)

[[17 64 73]
 [39 42 10]
 [83 42 19]]

[[28 57 14]
 [55 98  3]
 [16 77 57]]


Determinant and inverse (if applicable)

In [30]:
print(np.linalg.det(x))
print()
print(np.linalg.det(y))
print()
print(np.linalg.inv(x))
print()
print(np.linalg.inv(y))

-122781.99999999993

11318.99999999998

[[-0.00307863 -0.00072486  0.01505107]
 [-0.01506736  0.04671695 -0.03744849]
 [ 0.0197586  -0.02180287  0.01451353]]

[[ 0.47309833 -0.27272727  0.23562152]
 [-0.1918014   0.12121212 -0.1099037 ]
 [-0.10610478  0.06060606 -0.03454369]]


# Additional Programs

# Program 1
Given the array ```arr = np.arange(1, 101).reshape(10, 10)```:

In [31]:
arr = np.arange(1, 101).reshape(10, 10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

Extract the first three rows and the last three columns.

In [32]:
arr[:3, -3:]

array([[ 8,  9, 10],
       [18, 19, 20],
       [28, 29, 30]])

Extract the diagonal elements.

In [33]:
np.diag(arr)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

# Program 2
Create a 3D NumPy array of shape (4, 5, 6) with random integers from 1 to 100. Perform the following:

In [35]:
arr = np.random.randint(1, 100, (4, 5, 6))
arr

array([[[36, 63, 89, 80, 85, 64],
        [45, 35, 46, 99, 28, 60],
        [46, 74, 18, 30, 27, 81],
        [44, 50, 32, 53, 55, 13],
        [65, 97, 98, 92, 75, 44]],

       [[97, 20, 89, 84, 34, 52],
        [64, 27, 12, 75, 90,  1],
        [26, 31, 47, 67, 25, 46],
        [76, 49, 24, 86, 15, 42],
        [51, 92, 73,  8, 24,  8]],

       [[73, 49, 19, 36, 87, 98],
        [69, 90, 87, 45, 82,  4],
        [95, 30, 48, 73, 71, 11],
        [11,  8, 11, 15, 63, 98],
        [ 9, 52, 82, 50,  6, 27]],

       [[73, 90, 63, 75, 68, 98],
        [31,  3, 88, 15, 70, 26],
        [90, 38, 21,  3, 65, 87],
        [ 3, 30,  5, 22, 76, 91],
        [24, 21, 72,  3, 36, 58]]])

Extract all elements from the second row of every 2D matrix along the first axis.

In [37]:
arr[:, 1, :]

array([[45, 35, 46, 99, 28, 60],
       [64, 27, 12, 75, 90,  1],
       [69, 90, 87, 45, 82,  4],
       [31,  3, 88, 15, 70, 26]])

Extract all elements from the last column of the third 2D matrix along the first axis.

In [38]:
arr[2, :, -1]

array([98,  4, 11, 98, 27])

# Program 3
Create a 4D array of shape (3, 4, 5, 6) with random floating-point numbers. Perform the following:

In [39]:
arr = np.random.rand(3, 4, 5, 6)
arr

array([[[[0.73722973, 0.54927501, 0.16865605, 0.78051108, 0.56007485,
          0.68054867],
         [0.75717697, 0.70132519, 0.89409295, 0.82783275, 0.5722055 ,
          0.35812093],
         [0.57102388, 0.87802719, 0.7852809 , 0.79490562, 0.15960251,
          0.50667415],
         [0.68617103, 0.92862227, 0.58338016, 0.12780209, 0.42409462,
          0.54786996],
         [0.92221977, 0.25925844, 0.43744979, 0.71072949, 0.99831845,
          0.63049158]],

        [[0.26343305, 0.20207433, 0.90911837, 0.54366531, 0.2379443 ,
          0.94319047],
         [0.72370929, 0.95453723, 0.30623814, 0.85713332, 0.80540945,
          0.65743957],
         [0.37475467, 0.06437394, 0.50029945, 0.04094003, 0.37984621,
          0.61194568],
         [0.64627278, 0.0761837 , 0.4891698 , 0.62097119, 0.64355162,
          0.42652573],
         [0.22729314, 0.39168538, 0.89110804, 0.86176485, 0.54437953,
          0.53682512]],

        [[0.94302444, 0.20786936, 0.98184385, 0.41885895, 0.583044

Extract every alternate row and column from the second and fourth dimensions.

In [40]:
arr[:, ::2, ::2, :]

array([[[[0.73722973, 0.54927501, 0.16865605, 0.78051108, 0.56007485,
          0.68054867],
         [0.57102388, 0.87802719, 0.7852809 , 0.79490562, 0.15960251,
          0.50667415],
         [0.92221977, 0.25925844, 0.43744979, 0.71072949, 0.99831845,
          0.63049158]],

        [[0.94302444, 0.20786936, 0.98184385, 0.41885895, 0.58304469,
          0.82487253],
         [0.18213145, 0.50366832, 0.20950056, 0.49114279, 0.03759721,
          0.63542813],
         [0.06214683, 0.5675268 , 0.45653512, 0.08514574, 0.3646076 ,
          0.76517903]]],


       [[[0.78007876, 0.47443009, 0.01764208, 0.60766341, 0.39384578,
          0.46630818],
         [0.6661811 , 0.33302852, 0.21713517, 0.27061557, 0.47714159,
          0.66112814],
         [0.46164086, 0.13878819, 0.16955575, 0.76435171, 0.47125953,
          0.51904938]],

        [[0.67793846, 0.07792084, 0.60496243, 0.60403012, 0.95177228,
          0.53248186],
         [0.64049141, 0.55811688, 0.85727255, 0.57350227, 0.90

Extract elements from every 2nd matrix along the first axis and every 3rd slice along the third dimension.

In [41]:
arr[::2, :, ::3, :]

array([[[[0.73722973, 0.54927501, 0.16865605, 0.78051108, 0.56007485,
          0.68054867],
         [0.68617103, 0.92862227, 0.58338016, 0.12780209, 0.42409462,
          0.54786996]],

        [[0.26343305, 0.20207433, 0.90911837, 0.54366531, 0.2379443 ,
          0.94319047],
         [0.64627278, 0.0761837 , 0.4891698 , 0.62097119, 0.64355162,
          0.42652573]],

        [[0.94302444, 0.20786936, 0.98184385, 0.41885895, 0.58304469,
          0.82487253],
         [0.59719568, 0.06374037, 0.67943282, 0.79198566, 0.61229943,
          0.93209417]],

        [[0.80874001, 0.53510984, 0.55626349, 0.74665005, 0.39865706,
          0.94979698],
         [0.67136484, 0.97651754, 0.76360382, 0.54399904, 0.84152246,
          0.02773815]]],


       [[[0.4840651 , 0.15874522, 0.9993073 , 0.91610963, 0.75556795,
          0.57915112],
         [0.16913724, 0.50475347, 0.73544688, 0.63949893, 0.0435913 ,
          0.78778991]],

        [[0.35766737, 0.62154479, 0.86648852, 0.58555227, 

# Program 4
Create a 2D array of shape (6, 8) with numbers from 1 to 48.

In [42]:
arr = np.arange(1, 49).reshape(6, 8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

Reverse the rows while keeping the columns in their original order.

In [43]:
arr[::-1, :]

array([[41, 42, 43, 44, 45, 46, 47, 48],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

Reverse the last three columns while keeping the rows in their original order.

In [44]:
arr[:, -1:-4:-1]

array([[ 8,  7,  6],
       [16, 15, 14],
       [24, 23, 22],
       [32, 31, 30],
       [40, 39, 38],
       [48, 47, 46]])

# Program 5
Create a 3D array of shape (3, 5, 5) with random integers from 10 to 99. Perform the following:

In [45]:
arr = np.random.randint(10, 100, (3, 5, 5))
arr

array([[[22, 78, 88, 98, 40],
        [65, 31, 76, 25, 71],
        [63, 69, 10, 71, 80],
        [42, 59, 31, 16, 32],
        [44, 43, 77, 61, 35]],

       [[29, 17, 99, 59, 95],
        [33, 35, 99, 83, 14],
        [67, 60, 79, 90, 32],
        [51, 49, 55, 71, 18],
        [22, 36, 56, 51, 31]],

       [[40, 93, 35, 88, 11],
        [62, 42, 30, 23, 72],
        [25, 90, 99, 88, 79],
        [51, 84, 20, 75, 75],
        [89, 92, 66, 95, 48]]])

Extract all elements from the array where the value is a multiple of 3.

In [49]:
arr[arr % 3 == 0]

array([78,  0,  0,  0, 63, 69,  0,  0, 42,  0, 99,  0, 33,  0, 99,  0,  0,
       51,  0, 18, 36, 51,  0, 93,  0, 42,  0, 72,  0,  0, 99, 51, 84,  0,
        0,  0, 66,  0, 48])

Replace all elements divisible by 5 with the value 0.

In [51]:
arr[arr % 5 == 0] = 0
arr

array([[[22, 78, 88, 98,  0],
        [ 0, 31, 76,  0, 71],
        [63, 69,  0, 71,  0],
        [42, 59, 31, 16, 32],
        [44, 43, 77, 61,  0]],

       [[29, 17, 99, 59,  0],
        [33,  0, 99, 83, 14],
        [67,  0, 79,  0, 32],
        [51, 49,  0, 71, 18],
        [22, 36, 56, 51, 31]],

       [[ 0, 93,  0, 88, 11],
        [62, 42,  0, 23, 72],
        [ 0,  0, 99, 88, 79],
        [51, 84,  0,  0,  0],
        [89, 92, 66,  0, 48]]])